---
title: "Introduction to rags2ridges"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**rags2ridges** is an R-package for *fast* and *proper* L2-penalized estimation of precison (and covariance) matrices also called **ridge estimation**. It also features the ability to shrink towards target matrices as well as a *fused* ridge method for simultaneuous estimation of multiple matrices. 
The package also features additional functions for post-processing the L2-penalized estimates --- useful for feature selection and when doing graphical modelling. The *fused* ridge estimation is useful when dealing with grouped data as when doing meta or integrative analysis.

This vignette provides a light introduction on how to get started with regular ridge estimation of precision matrices.


# Getting started


## Package installation


## Lightweight theoretical primer


## Ridge estimation

### Precision matrix


### Covariance matrix


## Gaussian graphical modeling and post processing


# Concluding remarks



