# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.armaPooledS <- function(Slist, ns, mle = 0L) {
    .Call('rags2ridges_armaPooledS', PACKAGE = 'rags2ridges', Slist, ns, mle)
}

.armaPooledP <- function(Plist, ns, mle = 0L) {
    .Call('rags2ridges_armaPooledP', PACKAGE = 'rags2ridges', Plist, ns, mle)
}

.armaRidgePAnyTarget <- function(S, target, lambda) {
    .Call('rags2ridges_armaRidgePAnyTarget', PACKAGE = 'rags2ridges', S, target, lambda)
}

.armaRidgePRotationInvariantTarget <- function(S, alpha, lambda) {
    .Call('rags2ridges_armaRidgePRotationInvariantTarget', PACKAGE = 'rags2ridges', S, alpha, lambda)
}

.armaRidgeP <- function(S, target, lambda) {
    .Call('rags2ridges_armaRidgeP', PACKAGE = 'rags2ridges', S, target, lambda)
}

.armaFusedUpdateI <- function(g0, Plist, Slist, Tlist, ns, lambda, lambdaF) {
    .Call('rags2ridges_armaFusedUpdateI', PACKAGE = 'rags2ridges', g0, Plist, Slist, Tlist, ns, lambda, lambdaF)
}

.armaFusedUpdateII <- function(g0, Plist, Slist, Tlist, ns, lambda, lambdaF) {
    .Call('rags2ridges_armaFusedUpdateII', PACKAGE = 'rags2ridges', g0, Plist, Slist, Tlist, ns, lambda, lambdaF)
}

.armaFusedUpdateIII <- function(g0, Plist, Slist, Tlist, ns, lambda, lambdaF) {
    .Call('rags2ridges_armaFusedUpdateIII', PACKAGE = 'rags2ridges', g0, Plist, Slist, Tlist, ns, lambda, lambdaF)
}

.armaRidgeP_fused <- function(Slist, ns, Tlist, lambda, lambdaF, Plist, maxit = 100L, eps = 1e-5, verbose = FALSE) {
    .Call('rags2ridges_armaRidgeP_fused', PACKAGE = 'rags2ridges', Slist, ns, Tlist, lambda, lambdaF, Plist, maxit, eps, verbose)
}

rmvnormal <- function(n, mu, sigma) {
    .Call('rags2ridges_rmvnormal', PACKAGE = 'rags2ridges', n, mu, sigma)
}

.armaRWishart <- function(n, sigma, nu) {
    .Call('rags2ridges_armaRWishart', PACKAGE = 'rags2ridges', n, sigma, nu)
}

.armaRInvWishart <- function(n, psi, nu) {
    .Call('rags2ridges_armaRInvWishart', PACKAGE = 'rags2ridges', n, psi, nu)
}

