# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armaRidgeSAnyTarget <- function(S, target, lambda) {
    .Call('rags2ridges_armaRidgeSAnyTarget', PACKAGE = 'rags2ridges', S, target, lambda)
}

armaRidgeSZeroTarget <- function(S, lambda) {
    .Call('rags2ridges_armaRidgeSZeroTarget', PACKAGE = 'rags2ridges', S, lambda)
}

armaRidgeSEqualDiagTarget <- function(S, target, lambda) {
    .Call('rags2ridges_armaRidgeSEqualDiagTarget', PACKAGE = 'rags2ridges', S, target, lambda)
}

